[package]
name = "frp-engine"
version = "0.1.0"
edition = "2024"
description = "Async neuro runtime for the infinite-db frp backend."
license = "MIT OR Apache-2.0"
repository = "https://github.com/joneseysinno/frp-engine.git"
documentation = "https://docs.rs/frp-engine"
keywords = ["graph", "engine", "runtime", "async", "frp"]
categories = ["asynchronous"]

[dependencies]
frp-domain = { version = "0.1.0", path = "../frp-domain" }
frp-weave = { version = "0.1.0", path = "../frp-weave" }
frp-plexus = { version = "0.1.0", path = "../frp-plexus" }
frp-signal = { version = "0.1.0", path = "../frp-signal" }
futures = "0.3"
rhai = { version = "1", features = ["sync"] }
thiserror = { workspace = true }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
